### ISSUE TITLE
TrackPlay display error on notification

### ISSUE THREAD

**Issue by chenft** [dooboolab/flutter_sound#290] opened 2020-04-15 09:22 UTC
### Version of flutter_sound
3.1.8
### Platforms you faced the error (IOS or Android or both?)
android

### Actual behavior
![277381586941987_ pic](https://user-images.githubusercontent.com/17562266/79321214-93f10400-7f3d-11ea-9231-f09be56698ed.jpg)
![277391586941988_ pic](https://user-images.githubusercontent.com/17562266/79321223-97848b00-7f3d-11ea-9f22-28e593ef1b9c.jpg)
![277401586941989_ pic](https://user-images.githubusercontent.com/17562266/79321230-99e6e500-7f3d-11ea-8dc8-3df8a9156ff3.jpg)

### Tested environment (Emulator? Real Device?)
real device

### Steps to reproduce the behavior
1.After I called startPlayerFromTrack, notification will show picture 1, albumArtUrl not show
2.When I tap pause on notification,will show picture 2.This time albumArtUrl is shown;
3.When I tap pause on foregraund, will show picture 3;EveryThing looks terrible

**Comment by Larpoux** [comment] 2020-04-15 09:38
OK. I will look to this issue.
(I am currently working on the lock-screen `Album Art` in the future version Flutter Sound 4.0.0)

**Comment by Larpoux** [comment] 2020-04-15 09:44
Is your Album Art a remote file (HTTP://...)  or a local file ?

**Comment by chenft** [comment] 2020-04-15 09:51
@Larpoux remote file

**Comment by chenft** [comment] 2020-04-15 10:10
@Larpoux 

> OK. I will look to this issue.
> (I am currently working on the lock-screen `Album Art` in the future version Flutter Sound 4.0.0)

I have'd read your article.
But you don't mention about pause or play callback on lock-screen.
When I use your trackplayer, I don't know how to listen pause or play event on lock-screen.
On the other hand, after I pause or play on lock-screen, I try to get audioplay.isPlaying value on foregraund, such as onPlayerStateChanged.
Unfortunately, audioplay status is always incorrect.
Did you support these features ? Or you have'd supported, but I don't figure out?

I also add whenPaused callback in startPlayerFromTrack, but it's not working

**Comment by Larpoux** [comment] 2020-04-15 11:06
If you want to handle PLAY/PAUSE from the lock-screen you must use the `whenPaused:` parameter in `startPlayerFromTrack()`.

- `audioPlayer.isPlaying` is true when playing (not paused)
- `audioPlayer.isplaying` is false when paused or stopped

Could you most a snippet of your code ?

**Comment by chenft** [comment] 2020-04-15 11:25
@Larpoux 

Map justData = {
      'track': Track(
                trackPath: item['song_url'],
                trackTitle: item['song_name'],
                trackAuthor: item['artist_name'],
                albumArtUrl: item['song_cover']
              ),
              ...item
    };


Future<String> result = audioPlayer.startPlayerFromTrack(
              songData['track'],
              whenFinished: () {
                print('I hope you enjoyed listening to this song');
                _next();
                setState(() {});
              },
              whenPaused:(res) {
                print(res);
                print(audioPlayer.playerState);
                setState(() {});
              },
              onSkipForward: () {
                print('Skip forward');
                _next();
              },
            );


whenPaused never trigger，but onSkipForward can trigger.

**Comment by Larpoux** [comment] 2020-04-15 11:27
`whenPaused()` does not have any argument. `res` is probably not good.

**Comment by chenft** [comment] 2020-04-16 08:00
@Larpoux 

> `whenPaused()` does not have any argument. `res` is probably not good.

But you have set parameters in your function definition
![63731587023672_ pic](https://user-images.githubusercontent.com/17562266/79429830-a54c1600-7ffa-11ea-8471-9281688c7167.jpg)

And I saw TrackPlayer's code, there might no place to trigger the whenpause function
![63711587023442_ pic](https://user-images.githubusercontent.com/17562266/79429945-c90f5c00-7ffa-11ea-9a8a-dc54601ddb63.jpg)
![63721587023493_ pic_hd](https://user-images.githubusercontent.com/17562266/79429951-cb71b600-7ffa-11ea-834c-d8b5aaeea581.jpg)

**Comment by Larpoux** [comment] 2020-04-16 08:05
Pause/Resume is handled in the super class (flutterSoundPlayer) : 
```
default : return super.channelMethodCallHandler(cal);
```

**Comment by chenft** [comment] 2020-04-16 08:31
@Larpoux  
okay.
But pause or resume never trigger when I debugger on FlautoPlayerPlugin's channelMethodCallHandler.

**Comment by Larpoux** [comment] 2020-04-16 08:44
I am going to look to that.

**Comment by chenft** [comment] 2020-04-16 08:47
@Larpoux 

> I am going to look to that.
> Which flutter_sound version do you use ?

3.1.8

**Comment by Larpoux** [comment] 2020-04-16 14:05
We need your logs and a recent snippet of your code.

We can only reproduce a bug on Android when we try to show a remote Album Art.
I am currently looking to that.

**Comment by Larpoux** [comment] 2020-04-16 21:13
@salvatore373 ,
We really hope that everything fine, for you.

Per favor, could you look to this bug ?
Actually, the Album Art is not displayed on Android when the App specify a remote URI file.
But it is displayed when the user hit 'Pause' on the lock screen.

Thank you very much if you can do something for that.

**Comment by salvatore373** [comment] 2020-04-16 21:25
@Larpoux I have already solved this problem in my fork of flutter_sound. Take a look at it
Could you please also take a look to my PR to your `flauto` project?

**Comment by Larpoux** [comment] 2020-04-16 21:31
Yes, I will.
But please do your PR on `flutter_sound` project and not anymore on `flauto`.
`flauto` has been merged into `Flutter Sound 3.x.x` and is dead, now.

Great if this bug has been fixed in your fork.
I worry a little bit for `Track Player` maintenance (`Track Player` is `flauto` name in the release version).

Have a good sleep.

**Comment by Larpoux** [comment] 2020-04-17 16:59
Hi @salvatore373 ,

Did you talk with Hyo about your PR ?

If you have a fix to suggest for our bug on Android when the Album Art is displayed it would be really great.

**Comment by salvatore373** [comment] 2020-04-17 17:15
I will make a new PR to flutter_code to implement all the changes I made in my fork. It will take some time because I have to adapt it to the new version of the code.

**Comment by Larpoux** [comment] 2020-04-17 17:17
Thank you, Salvatore.

Your PR will be very good for our beta or dev version of flutter_sound.
But actually we have a bug on the released version(3.1.10), and we really need a patch to fix that.

**Comment by Larpoux** [comment] 2020-04-17 17:21
Actually we maintain three branches :  
- A release branch (3.x.x)
- A beta branch (4.0.0)
- And a dev branch.

A complete PR is OK for the dev branch.
But on the release branch (master) we need a patch.

**Comment by Larpoux** [comment] 2020-04-19 18:16
Hi, @salvatore373 ,

Do you have any (good) news about a fix for this bug ?
Some users are actually waiting for a fix.

**Comment by Larpoux** [comment] 2020-04-24 16:39
Hi @chenft .
The Flutter Sound V4.0.0 has just been released.

This version fixes the bug which was that the remote Album Art was not correctly displayed on the lock screen.

Please re-open this issue if this does not correctly answer your problems

**Closed by Larpoux** 2020-04-24 16:39 UTC
Labels: bug
