### ISSUE TITLE
Sound quality

### ISSUE THREAD

**Issue by shanzhenghan** [dooboolab/flutter_sound#95] opened 2019-06-07 07:42 UTC
The recorded sound sounds echoed and distorted. In a large cave, for example, the volume is very small.

**Comment by kbanta11** [comment] 2019-06-12 15:53
I'm having the same issue on android

**Comment by MsXam** [comment] 2019-06-18 12:09
I have been using this package since early 1.x and the problem even occurred then. The problem is on Android only which makes this plugin unusable.

Here is another reference of the issue :- 

https://github.com/dooboolab/flutter_sound/issues/79

There has been no activity on this bug for a very long time so it would appear the package is no longer maintained which is a pity.

Does anyone know of a similar working plugin ?

**Comment by SethThoburn** [comment] 2019-06-22 03:18
There's a fix mentioned for the garbled quality in that issue #79:
```startRecorder(uri, androidEncoder: AndroidEncoder.AMR_WB);```

**Comment by MsXam** [comment] 2019-06-22 10:15
Unfortunately the fix mentioned in that issue doesnt resolve the poor sound quality (garbage sound and very low sound volume) - have tested on Samsung S8+ & S10+ live devices. Even 1.42 exhibits the same problem so the issue is far from fixed. I have created a Xamarin plugin for iOS & Android and I get perfect sound without any distortion. I may consider moving to dart and creating a universal sound plugin that has all of the functionality of this plugin less the many issues reported.

**Comment by MsXam** [comment] 2019-06-22 11:26
P.s

re : https://github.com/dooboolab/flutter_sound/issues/95#issuecomment-504622496

The fix doesnt allow sound files to be shared between iOS/Android - recording in anything other then ...aac.. on Android will not play on iOS

**Comment by hyochan** [comment] 2019-06-22 16:19
@MsXam Hi. If you were the maintainer of the `Xamarin plugin`, hope you can guide me here to maintain the library. I've been having hard time maintaining serveral other libraries today (and even suffering from insomnia 😞). I was so busy these days on my main job.

**Comment by Matheus-Perez** [comment] 2019-06-27 22:06
> AndroidEncoder

I tested it now, with this recommended and worked correctly

**Comment by Matheus-Perez** [comment] 2019-06-27 22:06
> There's a fix mentioned for the garbled quality in that issue #79:
> `startRecorder(uri, androidEncoder: AndroidEncoder.AMR_WB);`

I tested it now, with this recommended and worked correctly

**Comment by MsXam** [comment] 2019-06-28 09:16
@Matheus-Perez https://github.com/dooboolab/flutter_sound/issues/95#issuecomment-506528747

As mentioned - previously , In Android, current version 1.42,  sound is not optimal and very faint as reported by several other users. As you know, writing great plugins means that they support 100% both platforms - I'm therefore unsure what your testing entails when you write  

_"I tested it now, with this recommended and worked correctly"_

Since Adaptive multi rate wide band encoding is not supported in iOS in which case recording on one device (say Android) and then being able to listen to that recording on another device (say iOS) with a recording format of AMR_WB will obviously not work with this plugin - I hope you can see this.

Like Hyo Chan Jang , I'm super busy moving a very large Enterprise Xamarin app over to Flutter but also trying to find time to migrate my **Xamarin Sound**  plugin over to  **Dart/Flutter**  where recording & playback work seamlessly in (iOS, Android, Mac, W10 etc).

FYI - The valid formats in iOS are defined here  

[codecs](https://developer.apple.com/library/archive/documentation/MusicAudio/Conceptual/CoreAudioOverview/CoreAudioEssentials/CoreAudioEssentials.html#//apple_ref/doc/uid/TP40003577-CH10-SW57)

and [Audio file formats](https://developer.apple.com/library/archive/documentation/MusicAudio/Conceptual/CoreAudioOverview/CoreAudioEssentials/CoreAudioEssentials.html#//apple_ref/doc/uid/TP40003577-CH10-SW57)
 
This plugin **(Flutter sound)** therefore needs to allow seamless & perfect interchangeable  recording and playback between its supported platforms (iOS & Android) and in its 1.42 form, it doesnt achieve that.

**Comment by phuchuynhStrong** [comment] 2019-07-03 08:29
After a lot of trials, I found something might help to improve sound quality on Android. The sound is better and can be play on iOS device. The fix I'm using `startRecorder(uri, androidEncoder: AndroidEncoder.AAC, bitRate: 128000, sampleRate: 96000,)`

**Comment by SethThoburn** [comment] 2019-07-03 20:35
On a similar note, I've been getting very good quality with the AndroidEncoder.AAC, a bitrate of 256000, and a sample rate of 44100

**Comment by darren-f5s** [comment] 2019-08-05 08:45
@MsXam Any chance you've made progress on the rewrite of the Xamarin Sound plugin?

**Comment by MsXam** [comment] 2019-08-11 11:41
@SethThoburn  bitRate of 256k and SampleRate of 44k is not conducive for writing cloud based enterprise apps where extremely small files are necessary to keep storage costs low as well as the time it takes to stream a file with these settings (even with compression enabled). A typical 6:21 sec AAC recording in Android with SampleRate 44k and bitRate 256k will produce a file of size 75k. This is 3 times the file size if we have SR of 16k and bitRate of 32k. Additionally - we have found ZERO improvement in sound quality when we adopt these settings (in Android). 

@shanzhenghan with your settings , still we find sound quality very poor on Android and file size as per what you have written , i.e expect higher file size with these settings

@darren-f5s We were in the middle of a few very large important sprints so could not factor in as much time as we would have liked, however - we now have some slack so expect to work on this again now.

**Comment by hamadmarri** [comment] 2019-09-06 09:44
Why not using ffmpeg plugin to convert audio formats after recording?

**Comment by ssbaval** [comment] 2019-10-23 19:37
This is really bad and cant believe how long this bug has been .... The sound quality is really poor in android - garbled. None of the recommendations work here - They increase the size of the AAC file by a factor of 10 which makes streaming to a cloud impossible and too costly and the sound quality still is not improved. ffmpeg is not feasible as it bloats an IPA or APK file considerably.

**Comment by hyochan** [comment] 2019-12-07 15:25
Coming from #79. I hope you to see [my reply](https://github.com/dooboolab/flutter_sound/issues/79#issuecomment-546671532)

**Closed** 2019-12-08 06:30 UTC
Labels: android, feature request

**Comment by hyochan** [comment] 2019-12-08 06:35
Please check out `1.6.0`
