### ISSUE TITLE
startRecording fails on android X ?

### ISSUE THREAD

**Issue by bsutton** [dooboolab/flutter_sound#203] opened 2020-01-24 00:02 UTC
## flutter doctor
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/bsutton/apps/flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/bsutton/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/bsutton/apps/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/bsutton/apps/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
When I call startRecording the system should start recording.

### Actual behavior
The call to startRecording fails silently.

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
Call startRecording.

So I've dug into the code and found the source of the error:
The method:
checkRecordPermission  in FlutterSoundPlugin.java (line 42) calls:
`reg.activity()`
which is returning a null.

Line 44 then passes the null activity to :
 ```ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.RECORD_AUDIO,}, 0);```

The call to requestPermissions then throws an NPE.

Looking at the documentation I suspect this is occurring as I'm running a later version of Flutter/Dart.

The documentation on `Registrar.activty()` has instructions for migrating a plugin from Flutters v1 embedding to Flutters v2 embedding. It would appear that flutter_sound is still using the v1 method which is why I suspect this bug is showing up now.

So it looks like the code needs to be migrated as per:

For instructions on migrating a plugin from Flutter's v1 Android embedding to v2, visit http://flutter.dev/go/android-plugin-migration

Can I also suggest that you put a try/catch block around each top level method so that you can log and report an appropriate error to the calling application rather than just failing silently.

**Comment by hyochan** [comment] 2020-01-24 04:48
Heya. I've just looked into your link and it looks like we currently need migration starting from flutter `1.12+`. I've just quickly add exception [following this] from `flutter sound 2.0.2`. Hope this can help for now. We'll do the migration when remaining `PR`'s are merged.

**Comment by Larpoux** [comment] 2020-01-24 15:39
I am running flutter_sound on flutter master branch (v1.14.4-pre.17) without any problem.
I propose to look to this issue ... and try to understand what is androidx ;-)

**Comment by Larpoux** [comment] 2020-01-24 19:30
Yes Brett @bsutton ,
You are totally right : your problem is tied to the Android recording permission.
I will look tomorrow if it is possible to fix your bug without having to migrate to Plugin V2.
I am afraid that migrating to V2 will give us some compatibility issues. And it will need tests to try to avoid regression.

**Comment by Larpoux** [comment] 2020-01-25 22:42
My actual thinking is that it is not flutter_sound job to take care of permissions.
If the developer wants to use flutter_sound to record something, it is HIS job to either declare the permission in his AndroidManifest.xml, or requesting himself the recording permission needed.

But if we decide to keep the actual behaviour (flutter_sound verify and request permission himself ), it would probably be better to do that on the Dart side (using package:permission_handler/permission_handler.dart) and not in the java side.

Hyo ? Do you think that I should code some Dart code for that ? Or do you think that we do not have to take care of permission ?

**Comment by bsutton** [comment] 2020-01-26 00:53
I think we should take care of permissions. If it can be done on the dart side that would be a much better idea as it makes maintenance easier.

**Comment by Larpoux** [comment] 2020-01-26 08:50
OK @bsutton : I am going to take care of that code.

PS: I am in the process of supporting both flutter  version (v2) of embedding  and flutter version (v1) of embedding. 
There is many, many tests to do with various versions of Android SDK and iOS SDK.
But I am pretty confident that I will be able to success.

**Comment by bsutton** [comment] 2020-01-26 09:18
I think it would be reasonable to create v3 which supports the V2 embedding
and leave V2 to support the v1 embedding

**Comment by Larpoux** [comment] 2020-01-26 09:22
Yes, this could be a good planing.
I am not a flutter expert, but my first tries to be compatible with V1 and V2 is encouraging.
Flutter documentation is good, and there is no much code to be compatible.

I will take you inform later (this evening or tomorrow) of my advancement.

**Comment by MichalMisiaszek** [comment] 2020-01-28 06:52
So I pulled latest version 2.0.3 and method 
`String  _file = await _flutterSound.startRecorder(uri: _soundFilename);`
seems to be doing nothing.

**Comment by bsutton** [comment] 2020-01-28 07:05
I don't believe 2.0.3 will fix the problem. There is a pr that looks closer
but I don't think it's a full solution either.

**Comment by MATTYGILO** [comment] 2020-02-21 11:54
> So I pulled latest version 2.0.3 and method
> `String _file = await _flutterSound.startRecorder(uri: _soundFilename);`
> seems to be doing nothing.

I am having the same issue as this. I have the most recent update and it is doing nothing.

**Comment by Larpoux** [comment] 2020-03-15 15:19
Flauto is now ready to be released.
Flauto is compatible with AndroidX and Android embbeded V2.
Could you check if this is OK for you when Flauto will be released ?
@hyochan : I hope soon 😺 !

**Comment by hyochan** [comment] 2020-03-25 12:40
Please comeback to this if you still face the issue in `3.0.0`. Closing for now.

**Closed by hyochan** 2020-03-25 12:40 UTC
Labels: good first issue, need migration

**Comment by anasssanba1** [comment] 2021-09-26 17:42
No permissions found in manifest for: []1
