### ISSUE TITLE
"output file has already been set"  exception

### ISSUE THREAD

**Issue by jianzi0307** [dooboolab/flutter_sound#125] opened 2019-08-25 20:28 UTC
flutter doctor
-------------
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.9.3-pre.56, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
[✓] VS Code (version 1.37.1)
[✓] Connected device (2 available)

• No issues found!
```

flutter_sound version
---------------------
```
flutter_sound: ^1.4.2
```

exception
---------------
```
D/FlutterSoundPlugin(16895): startRecorder
E/MediaRecorder(16895): output file has already been set
E/FlutterSoundPlugin(16895): Exception:
E/FlutterSoundPlugin(16895): java.lang.IllegalStateException
E/FlutterSoundPlugin(16895): 	at android.media.MediaRecorder._setOutputFile(Native Method)
E/FlutterSoundPlugin(16895): 	at android.media.MediaRecorder.prepare(MediaRecorder.java:859)
E/FlutterSoundPlugin(16895): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.startRecorder(FlutterSoundPlugin.java:164)
E/FlutterSoundPlugin(16895): 	at com.dooboolab.fluttersound.FlutterSoundPlugin.lambda$onMethodCall$0(FlutterSoundPlugin.java:67)
E/FlutterSoundPlugin(16895): 	at com.dooboolab.fluttersound.-$$Lambda$FlutterSoundPlugin$Uw7hmMVnMhHSlTmtp8I_WAUlmZE.run(lambda)
E/FlutterSoundPlugin(16895): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
E/FlutterSoundPlugin(16895): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/FlutterSoundPlugin(16895): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/FlutterSoundPlugin(16895): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/FlutterSoundPlugin(16895): 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by michalyashpe** [comment] 2019-09-10 08:00
I experience the same issue

**Comment by hyochan** [comment] 2019-09-14 18:55
Does this also happen in `1.4.4`? I've just tried myself in the `example` and can't reproduce this.

**Comment by cs118651** [comment] 2019-09-30 06:04
same issue on Android HUAWEI HONOR 9X

**Comment by cs118651** [comment] 2019-09-30 06:13
> same issue on Android HUAWEI HONOR 9X

I changed version from v1.4.5 to v1.4.4 and the issue is disappear

**Comment by sayhicoelho** [comment] 2019-12-03 19:32
Same issue here

**Comment by hyochan** [comment] 2020-01-24 05:54
What about in our recent version `2.0.3`? We've made some fixes related to this.

**Comment by Larpoux** [comment] 2020-04-08 11:51
Please, feel free to re-open this issue if you thin it has not been fixed by recent versions.

**Closed by Larpoux** 2020-04-08 11:51 UTC
Labels: android, help wanted
